name: Running Deployment Pipeline
run-name: ${{github.actor}} in ${{github.ref}}

on:
    push: 
      branches:
          - main

jobs: 
    deploying:
        runs-on: ubuntu-latest
        steps:         
            - name: Checkout Repository
              uses: actions/checkout@v4
          
            - name: Install Dependencies
              run: npm install
          
            - name: Build Application
              run: npm run build
          
            - name: Check Build Status
              if: ${{ success() }}
              run: echo "Build successful"
            
            - name: Display Build Failure Cause
              if: ${{ failure() }}
              run: echo "Build failed due to ${{ job.status }}"

            - name: 📂 Sync files and deploy via FTP
              uses: SamKirkland/FTP-Deploy-Action@4.3.5
              with:
                server: ${{ secrets.OWNER_FTP_SERVER }}
                username: ${{ secrets.OWNER_FTP_USERNAME }}
                password: ${{ secrets.OWNER_FTP_PASSWORD }}




