name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # Add steps for running tests if needed
      
      - name: Deploy to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.OWNER_FTP_SERVER }}
          username: ${{ secrets.OWNER_FTP_USERNAME }}
          password: ${{ secrets.OWNER_FTP_PASSWORD }}
          server-dir: /public_html/futsal_owner/
